name: POI CICD
env:
  poi_path: apis/poi/**
  registry: openhack8acr.azurecr.io
  repository: poi2
  docker_path: apis/poi/web/Dockerfile
  staging_url: https://openhack8poi-staging.azurewebsites.net
  prod_url: https://openhack8poi.azurewebsites.net
  resource_group: openhack8rg
  webapp_name: openhack8poi
  build_name: POI

on:
  push:
    branches: [ master ]
    paths: 
      - apis/poi/**  
      - .github/workflows/poi.yml
  pull_request:
    branches: [ master ]
    paths: 
      - apis/poi/**
      - .github/workflows/poi.yml

jobs:

  docker_build_and_push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
   # needs: build_and_test
    steps:
    - uses: actions/checkout@v2

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'Login to ACR'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USER }}
        password: ${{ secrets.ACR_KEY }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
       file: web/Dockerfile
       push: true
       tags: openhack8acr.azurecr.io/poi2:latest
  
  

# https://docs.microsoft.com/en-us/azure/container-instances/container-instances-github-action
