name: POI CICD
env:
  poi_path: apis/poi/**
  registry: openhack8acr.azurecr.io
  repository: poi
  docker_path: apis/poi/web
  staging_url: https://openhack8poi-staging.azurewebsites.net
  prod_url: https://openhack8poi.azurewebsites.net
  resource_group: openhack8rg
  webapp_name: openhack8poi
  build_name: POI

on:
  push:
    branches: [ master ]
    paths: 
      - apis/poi/**  
      - .github/workflows/poi.yml
  pull_request:
    branches: [ master ]
    paths: 
      - apis/poi/**
      - .github/workflows/poi.yml

jobs:

  docker_build_and_push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
   # needs: build_and_test
    steps:
    - uses: actions/checkout@v2

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
#    - name: 'Login to ACR'
#      uses: azure/docker-login@v1
#      with:
#        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
#        username: ${{ secrets.ACR_USER }}
#        password: ${{ secrets.ACR_KEY }}

    - name: Docker build
      run: docker build -t $registry/$repository:${{github.run_number}} --build-arg build_version=${{github.run_number}} $docker_path

    - name: Docker Push
      run: docker push $registry/$repository:${{github.run_number}}  
  

# https://docs.microsoft.com/en-us/azure/container-instances/container-instances-github-action
