name: User Profile CICD

env:
  registry: openhack8acr.azurecr.io
  repository: VodafDev/apis/userprofile
  docker_path: apis/user-java
  staging_url: https://openhack8userprofile-staging.azurewebsites.net
  prod_url: https://openhack8userprofile.azurewebsites.net
  resource_group: openhack8rg
  webapp_name: openhack8userprofile
  build_name: User Profile
  webv_path: apis/userprofile/webvalidate

on:
  push:
    branches: [ master ]
    paths: 
      - apis/userprofile/**  
      - .github/workflows/userprofile.yml
  pull_request:
    branches: [ master ]
    paths: 
      - apis/userprofile/**
      - .github/workflows/userprofile.yml

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apis/userprofile

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - uses: actions/github-script@0.9.0
      if: failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
            body: body
          });

