# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: User JAVA CICD

env:
  registry: docker.pkg.github.com
  repository: hattan/openhack-devops-team-gh/api-user-java
  docker_path: apis/user-java
  staging_url: https://openhackxv61mxh2userjava-staging.azurewebsites.net/
  prod_url: https://openhackxv61mxh2userjava.azurewebsites.net/
  resource_group: openhackxv61mxh2rg
  webapp_name: openhackxv61mxh2userjava
  build_name: User Java
  webv_path: apis/user-java/webvalidate


on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
